export interface Favorite {
  id: string; // ID of the favorite document (optional, can be auto-generated by Firestore)
  userId: string; // ID of the User who favored the Places
  vacationIds: string[]; // IDs of the favorites Places
  createdAt: Date; // Timestamp indicating when the favorite was created
}
